//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionedFurniture
    {
        public int CommissionedFurnituresId { get; set; }
        public int OrdersId { get; set; }
        public int FurnitureId { get; set; }
        public int ColorsId { get; set; }
        public int RawMaterialsId { get; set; }
        public Nullable<int> AmountCommissionedFurnitures { get; set; }
        public Nullable<int> HeightCommissionedFurnitures { get; set; }
        public Nullable<int> WidthCommissionedFurnitures { get; set; }
        public Nullable<int> DepthCommissionedFurnitures { get; set; }
        public virtual color color { get; set; }
        public virtual Furniture Furniture { get; set; }
        public virtual Order Order { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
    }
}
