//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectZUEntities : DbContext
    {
        public ProjectZUEntities()
            : base("name=ProjectZUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ColorForFurniture> ColorForFurnitures { get; set; }
        public virtual DbSet<color> colors { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Factory> Factories { get; set; }
        public virtual DbSet<Furniture> Furnitures { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<RawMaterial> RawMaterials { get; set; }
        public virtual DbSet<TypesOfService> TypesOfServices { get; set; }
        public virtual DbSet<CommissionedFurniture> CommissionedFurnitures { get; set; }
    }
}
